name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Creating kind cluster 
        uses: helm/kind-action@v1.0.0-rc.1

      - name: Deploy an application
        run: |
          kubectl apply -f https://k8s.io/examples/application/deployment.yaml

      - name: Running Litmus pod delete chaos experiment
        uses: litmuschaos/github-chaos-actions@v0.3.1
        env:
          ##Pass kubeconfig data from secret in base 64 encoded form 
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          ##If litmus is not installed
          INSTALL_LITMUS: true
          ##Give application info under chaos
          APP_NS: default
          APP_LABEL: run=nginx
          APP_KIND: deployment
          EXPERIMENT_NAME: pod-delete
          ##Custom image can also been used
          EXPERIMENT_IMAGE: litmuschaos/go-runner
          EXPERIMENT_IMAGE_TAG: latest
          IMAGE_PULL_POLICY: Always           
          TOTAL_CHAOS_DURATION: 30
          CHAOS_INTERVAL: 10
          FORCE: false
          ##Select true if you want to uninstall litmus after chaos
          LITMUS_CLEANUP: true
