name: test-main

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Test1
        id: test1
        continue-on-error: true
        run: |
          throw "This is an exception message."
          
      - name: Test2
        id: test2
        run: |
          echo lol
                    
      - name: Result
        run: |
          echo [ >> tests-status.json
  
          for i in steps.test1.outcome test2
          do
            echo "{\"$i\": ${{ steps.test1.outcome }}}," >> tests-status.json
            echo "{\"$i\": ${{ steps.test2.outcome }}}," >> tests-status.json
          done
          
          echo ] >> tests-status.json
          
          cat tests-status.json
