name: test-main

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Test1
        id: test1
        run: |
          echo lol
          
      - name: Test2
        id: test2
        if: ${{ always() }}
        run: |
          throw "This is an exception message."
                    
      - name: Result
        run: |
          echo [
          echo "test1: ${{ steps.test1.conclusion }}," >> tests-status.json
          echo "test2: ${{ steps.test2.conclusion }}," >> tests-status.json
          echo ]
          cat tests-status.json
