name: test-main

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Fail
        run: |
          throw "Test Failed"
          echo ${{ success() }} >> tests-status.json
      - name: Succ
        if: ${{ always() }}
        run: |
          echo ${{ success() }} >> tests-status.json
      - name: Result
        run: |
          cat tests-status.json
