name: chaos

on:
  push:
    branches: [ chaos ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        
      - name: Save test.txt
        run: echo test > test.txt
        
      - name: Commit and push
        run: |
          git config --global user.name 'gp185144'
          git config --global user.email '84555872+gp185144@users.noreply.github.com'
          git add .
          git commit -m "Github action artifacts"
          git push
