name: test-main

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: First step
        run: |
          echo yay
          
      - id: fail
        run: |
          throw "This is an exception message."
          
      - name: Succ
        id: succ
        if: ${{ always() }}
        run: |
          echo ${{ steps.fail.conclusion }}
          
      - name: Succ2
        if: ${{ always() }}
        run: |
          echo ${{ steps.succ.conclusion }}
          
#       - name: Result
#         run: |
#           cat tests-status.json
