name: test-main

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Test start timestamp
        run: |
          echo "[ $(date +%s) ," >> tests-log.json
          
      - name: Test1
        id: test1
        continue-on-error: true
        run: |
          throw "This is an exception message."      
      - name: Test log
        run: |
          echo "{ \"name\": ${NAME}, \"status\": ${STATUS}, \"end\": $(date +%s) }," >> tests-log.json
        env:
          NAME: Test 1
          STATUS: ${{ steps.test1.outcome }}
          
      - name: Test2
        id: test2
        run: |
          echo lol
      - name: Test log
        run: |
          echo "{ \"name\": ${NAME}, \"status\": ${STATUS}, \"end\": $(date +%s) }," >> tests-log.json
        env:
          NAME: Test 2
          STATUS: ${{ steps.test2.outcome }}
          
      - name: Test end timestamp
        run: |
          echo "$(date +%s) ]" >> tests-log.json
                    
      - name: Result
        run: |          
          cat tests-status.json
