name: test-main

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
#       - name: Fail
#         run: |
#           throw "Test Failed"
#           echo $STATUS >> tests-status.json
#         env:
#           STATUS: ${{ success() }}
          
      - name: Succ
        if: ${{ always() }}
        env:
          STATUS: ${{ success() }}
        run: |
          echo $STATUS >> tests-status.json
          
      - name: Result
        run: |
          cat tests-status.json
