name: test-main

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: First step
        run: |
          echo yay
          
      - name: Fail
        run: |
          throw "This is an exception message."
          
      - name: Succ
        continue-on-error: true
        run: |
          echo ${{ steps.conclusion }}
          
#       - name: Result
#         run: |
#           cat tests-status.json
