name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Installing Prerequisites (KinD Cluster)
        uses: engineerd/setup-kind@v0.5.0
        with:
            version: "v0.7.0"

      - name: Deploy application
        run: |
          kubectl apply -f https://k8s.io/examples/application/deployment.yaml

      - name: Setting up kubeconfig ENV for Github Chaos Action
        run: echo ::set-env name=KUBE_CONFIG_DATA::$(base64 -w 0 ~/.kube/config)
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - name: Setup Litmus
        run: |
          kubectl create ns litmus
          kubectl apply -f https://litmuschaos.github.io/litmus/2.0.0-Beta/litmus-2.0.0-Beta.yaml

      - name: Verify litmus
        run: |
          kubectl get pods
          kubectl get pods -n litmus

      - name: Running Litmus pod delete chaos experiment
        uses: litmuschaos/github-chaos-actions@v0.3.1
        env:
          ##Pass kubeconfig data from secret in base 64 encoded form 
          KUBE_CONFIG_DATA: ${{ env.KUBE_CONFIG_DATA }}
          ##Give application info under chaos
          APP_NS: default
          APP_LABEL: run=nginx
          APP_KIND: deployment
          EXPERIMENT_NAME: pod-delete
          ##Custom image can also been used
          EXPERIMENT_IMAGE: litmuschaos/go-runner
          EXPERIMENT_IMAGE_TAG: latest
          IMAGE_PULL_POLICY: Always           
          TOTAL_CHAOS_DURATION: 30
          CHAOS_INTERVAL: 10
          FORCE: false
          ##Select true if you want to uninstall litmus after chaos
          LITMUS_CLEANUP: true
