name: test-main

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: First step
        run: |
          echo yay
          
      - name: Succ
        if: ${{ always() }}
        env:
          STATUS: ${{ success() }}
        run: |
          echo $STATUS >> tests-status.json
          
      - name: Result
        run: |
          cat tests-status.json
