name: test-main

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      PROM_PATH: ./
    
    steps:
      - name: Test save
        run: |
          echo lol > ${{ env.PROM_PATH }}${FILE_NAME}
        env:
          FILE_NAME: test.json
      
      - name: Show
        run: |
          cat test.json

